name: Continuous Integration

on:
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Test with iDFlakies
        run: mvn verify
