name: Continuous Integration Ubuntu 22.04

on:
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Test with iDFlakies
        run: mvn verify

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ${{ github.workspace}}/.dtfixingtools/detection-results
